export interface Env {
  ADMIN_KEY: string,
  DB_HOST: string,
  DB_NAME: string,
  DB_USER: string,
  DB_PASS: string,
  TOKEN_SEND_GRID: string,
  EMAIL_NOTIFICATIONS: string,
  SYSTEM_NAME: string,
  JWT_KEY: string,
  PRIVATE_AWS_KEY: string,
  PRIVATE_AWS_ACCESS: string,
  AWS_BUCKET: string,
  AWS_FILE_VIEWS: string,
}
